name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Replace environment variables
      run: |
        sed -i 's/window.FIREBASE_API_KEY/"${{ secrets.FIREBASE_API_KEY }}"/g' index.html
        sed -i 's/window.FIREBASE_AUTH_DOMAIN/"${{ secrets.FIREBASE_AUTH_DOMAIN }}"/g' index.html
        sed -i 's/window.FIREBASE_PROJECT_ID/"${{ secrets.FIREBASE_PROJECT_ID }}"/g' index.html
        sed -i 's/window.FIREBASE_STORAGE_BUCKET/"${{ secrets.FIREBASE_STORAGE_BUCKET }}"/g' index.html
        sed -i 's/window.FIREBASE_MESSAGING_SENDER_ID/"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"/g' index.html
        sed -i 's/window.FIREBASE_APP_ID/"${{ secrets.FIREBASE_APP_ID }}"/g' index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
